/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import SQL.conexion_basedatos;
import SQL.metodosBaseDD;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Agustin
 */
public final class frm_Login extends javax.swing.JFrame {

    /**
     * Creates new form frm_Login
     */
    double dni;
    
    public frm_Login() {
        initComponents();
        setLocationRelativeTo(null);
        iconoDelPrograma();
        //ajustarLogo();
        lblFondo();
    }
    private static Connection conexion;
    private static PreparedStatement sentenciaPreparada;
    private static ResultSet resultado; //result de cada consulta a bdd
    metodosBaseDD instancia = new metodosBaseDD();
    frm_Menu_Principal menuPrincipal = new frm_Menu_Principal();
    
    public void iconoDelPrograma() {
        URL url = getClass().getResource("/imagenes/icono_del_programa.png");
        ImageIcon imagenDelPrograma = new ImageIcon(url);
        setIconImage(imagenDelPrograma.getImage());
    }

    /*public void ajustarLogo() {
        ImageIcon logoJava;
        logoJava = new ImageIcon(getClass().getResource("/imagenes/gitlogo.jpg"));
        Icon icono = new ImageIcon(logoJava.getImage().getScaledInstance(lblLogoJava.getWidth(), lblLogoJava.getHeight(), Image.SCALE_SMOOTH));
        lblLogoJava.setIcon(icono);
    }*/

    public void btnAceptarLbl() {
        ImageIcon lblIcono;
        lblIcono = new ImageIcon(getClass().getResource("/imagenes/aceptarAzul.png"));
        Icon iconoLbl = new ImageIcon(lblIcono.getImage().getScaledInstance(lblAceptarSalirAzul.getWidth(), lblAceptarSalirAzul.getHeight(), Image.SCALE_SMOOTH));
        lblAceptarSalirAzul.setIcon(iconoLbl);
        btnAceptar.setBackground(new Color(2, 187, 98));
    }

    public void btnCancelarLbl() {
        ImageIcon lblIcono;
        lblIcono = new ImageIcon(getClass().getResource("/imagenes/salirAzul.png"));
        Icon iconoLbl = new ImageIcon(lblIcono.getImage().getScaledInstance(lblAceptarSalirAzul.getWidth(), lblAceptarSalirAzul.getHeight(), Image.SCALE_SMOOTH));
        lblAceptarSalirAzul.setIcon(iconoLbl);
        btnSalir.setBackground(new Color(249, 58, 7));
    }

    public void salirDeBoton() {
        btnAceptar.setBackground(Color.white);
        btnSalir.setBackground(Color.white);
        lblAceptarSalirAzul.setIcon(null);
    }
    public void lblFondo(){
        ImageIcon lblFondoVerde;
        lblFondoVerde = new ImageIcon(getClass().getResource("/imagenes/javafondo.jpg"));
        Icon iconoLbl = new ImageIcon(lblFondoVerde.getImage().getScaledInstance(lblFondo.getWidth(), lblFondo.getHeight(), Image.SCALE_SMOOTH));
        lblFondo.setIcon(iconoLbl);
    }
    public void validarDniContraseña(double dni, String contraseña){
        
        String mensaje = metodosBaseDD.buscarDniDos(dni, contraseña);
        String nombre = null;
        String apellido = null;
        if(mensaje.equals("Correcto")){
            try {
                conexion = conexion_basedatos.conexionALaBase();
                String consulta = "SELECT nombre, apellido FROM datos_empleado WHERE dni = ?";
                sentenciaPreparada = conexion.prepareStatement(consulta);
                sentenciaPreparada.setDouble(1, dni);
                resultado = sentenciaPreparada.executeQuery();
                if(resultado.next()){
                    nombre = resultado.getString("nombre");
                    apellido = resultado.getString("apellido");
                }
            } catch (SQLException e) {
                System.out.println("Error: " + e);
            }
            instancia.datosFecha(dni, nombre, apellido);
            JOptionPane.showMessageDialog(null, "Bienvenidx \n" + nombre + " " + apellido + " ");
            menuPrincipal.lblNombreSesion.setText(nombre + " " + apellido + "");
            menuPrincipal.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Error al conectar a la base, verifique Dni o Contraseña");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        btnSalir = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        lblAceptarSalirAzul = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acceso al sistema");
        setMaximumSize(new java.awt.Dimension(420, 570));
        setMinimumSize(new java.awt.Dimension(420, 570));
        setPreferredSize(new java.awt.Dimension(420, 570));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 420, 140, 40);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dni:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 380, 120, 40);

        txtDni.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDniKeyTyped(evt);
            }
        });
        getContentPane().add(txtDni);
        txtDni.setBounds(160, 390, 210, 24);

        txtContraseña.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        getContentPane().add(txtContraseña);
        txtContraseña.setBounds(160, 430, 210, 24);

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(new javax.swing.border.MatteBorder(null));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(150, 470, 100, 60);

        btnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        btnAceptar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(new javax.swing.border.MatteBorder(null));
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAceptarMouseExited(evt);
            }
        });
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(30, 470, 100, 60);
        getContentPane().add(lblAceptarSalirAzul);
        lblAceptarSalirAzul.setBounds(300, 460, 70, 60);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/javafondo.jpg"))); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, -170, 410, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseExited
        salirDeBoton();
    }//GEN-LAST:event_btnAceptarMouseExited

    private void btnAceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseEntered
        btnAceptarLbl();
    }//GEN-LAST:event_btnAceptarMouseEntered

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        btnCancelarLbl();
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        salirDeBoton();
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        dni = Double.parseDouble((String)txtDni.getText());
        validarDniContraseña(dni, txtContraseña.getText());
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtDniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyTyped
         if (txtDni.getText().length() == 8) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtDniKeyTyped

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAceptarSalirAzul;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtDni;
    // End of variables declaration//GEN-END:variables
}
